# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e55a867fa2c287037caf69e50c9b9bb4df0c6a064364382996c1ff4ede6a00126d9a3e033d911397f302d9db9f4b4b671a0272c6b32ab8e29a37f2a290e4b3b3

test:
  secret_key_base: 2a2dad826ce2d7ec8eeb8cfc10f57a83354381d4f6c85a72e7a83983a12a37951630cb5665385d5fbff0bef41bb9d9b592cbd0ef1db7b31b3b4f75343123fd2c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
